# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Playground

on:
  workflow_dispatch:

jobs:
  play:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_PLAY }}
      run: |
        PKG_VER=0.0.0-play.$(date +%s)
        pnpx tsx nppr/bin.ts tests/__fixtures__/barhop-0.0.0-PLACEHOLDER.tgz --repack --name @canary-109cafe/nppr-play-1 --version "$PKG_VER" --output 1.tgz --provenance 1.sigstore
        pnpx tsx nppr/bin.ts tests/__fixtures__/barhop-0.0.0-PLACEHOLDER.tgz --repack --name @canary-109cafe/nppr-play-2 --version "$PKG_VER" --output 2.tgz --provenance 2.sigstore
        ls -allh *.tgz *.sigstore
        pnpx tsx nppr/bin.ts 1.tgz --provenance-from 1.sigstore --publish  --add-fields.readmeFilename 'PACKAGE.md' --tag latest
        pnpx tsx nppr/bin.ts 2.tgz --provenance-from 2.sigstore --publish  --add-fields.readmeFilename 'PACKAGE.md' --tag latest
